instructlab/sdg

pyproject.toml

Fix website URL and remove some things which don't apply here.

Fixes to pyproject.toml

---

requirements.txt
src/instructlab/sdg/generate_data.py
src/instructlab/sdg/utils.py

This changed in the instructlab repo, so match it.

Rename instructlab.config to instructlab.configuration

---

README.md

Did this in a recent PR for `eval`

Add action badges to README

---

src/instructlab/sdg/generate_data.py

Signed-off-by: Costa Shulyupin <costa.shul@redhat.com>

links to openai, rouge_scorer tokenize docs or src

---

src/instructlab/sdg/iterblock.py

iterblock: remove duplicate line of code

---

src/instructlab/sdg/generate_data.py

File was being saved as `.json`, but contents are actually a list of jsons

Update messages datafile extension to be .jsonl

---

src/instructlab/sdg/utilblocks.py
tests/test_sample_populator_block.py

This has apparently been broken since commit 9d92548.

Fix SamplePopulatorBlock

---

src/instructlab/sdg/__init__.py
src/instructlab/sdg/pipeline.py
src/instructlab/sdg/utilblocks.py
tests/test_utilblocks.py

"DuplicateColumns", "FlattenColumnsBlock",
"RenameColumns", "SetToMajorityValue"
Closes #175
Closes #176
Closes #177
Closes #178

Add 4 new pipeline blocks

---

src/instructlab/sdg/eval_data.py

As the name suggests
Fixes #192

Make metric_list a list

---

src/instructlab/sdg/pipeline.py

The string should be formatted to to include {block_type}

Fix logging string formatting

---

src/instructlab/sdg/datamixing.py
src/instructlab/sdg/pipeline.py
src/instructlab/sdg/utilblocks.py
src/instructlab/sdg/utils/pandas.py

Add utility function to convert from Pandas dataframe to Hugging Face dataset

---

src/instructlab/sdg/pipelines/schema/v1.json

"config_paths" is a list of a list of strings, each entry is a path followed by a selector.
Fixes #210

Update ConditionalLLMBlock's config_paths schema

---

src/instructlab/sdg/eval_data.py

Fix the mmlubench paths to make it concise

---

src/instructlab/sdg/generate_data.py

Currently it is /usr/share/instructlab/sdg and we may want other SDG stuff in this directory.

Move system pipelines to /usr/share/instructlab/sdg/pipelines

---

src/instructlab/sdg/llmblock.py

Add gen_kwargs support for ConditionalLLMBlock

---

src/instructlab/sdg/block.py
src/instructlab/sdg/checkpointing.py
src/instructlab/sdg/datamixing.py
src/instructlab/sdg/eval_data.py
src/instructlab/sdg/filterblock.py
src/instructlab/sdg/importblock.py
src/instructlab/sdg/llmblock.py
src/instructlab/sdg/pipeline.py
src/instructlab/sdg/sdg.py
src/instructlab/sdg/utilblocks.py
tests/conftest.py
tests/test_checkpointing.py
tests/test_datamixing.py
tests/test_default_pipeline_configs.py
tests/test_filterblock.py
tests/test_importblock.py
tests/test_llmblock.py
tests/test_pipeline.py
tests/test_sample_populator_block.py
tests/test_utilblocks.py

Adding missing license identifiers

Add missing license identifiers

---

src/instructlab/sdg/datamixing.py
src/instructlab/sdg/eval_data.py
src/instructlab/sdg/filterblock.py
src/instructlab/sdg/pipeline.py
src/instructlab/sdg/utils/chunking.py
src/instructlab/sdg/utils/pandas.py
tests/test_chunking.py
tests/test_utilblocks.py

Fixing typos

---

.github/workflows/e2e-nvidia-a10g-x4.yml
.github/workflows/e2e.yml

Old option was removed here: https://github.com/instructlab/instructlab/pull/1937/files

Fix e2e by removing old option

---

src/instructlab/sdg/datamixing.py

Fix selection logic for distractor documents 

---

tests/test_datamixing.py

When picking additional contexts to act as golden or distractor documents, we had a bug where the answer document wasn't always being added. This was fixed in PR #252, and this just adds some additional tests in that area to prevent regression.

Add more tests for golden/distractor context picking

---

.github/mergify.yml
.github/workflows/actionlint.yml
.github/workflows/e2e-nvidia-t4-x1.yml
.github/workflows/lint.yml

Enable auto merging for PRs with >= 2 approvals

chore: add auto-merging policy for SDG

---

src/instructlab/sdg/llmblock.py

the new stop token was seen to have degraded SDG results, remove this

fix: remove stop token from mixtral

---

src/instructlab/sdg/generate_data.py
tests/test_generate_data.py

This PR parametrizes the system prompt so that users of SDG can pass their own system prompt in to the SDG process
fixes: #336

feat: parametrize system prompt

---

src/instructlab/sdg/datamixing.py

Data mix fix

---

src/instructlab/sdg/pipelines/full/knowledge.yaml

Add [End] to parser cleanup tags

---

CHANGELOG.md
requirements.txt

fix: Remove unused PyTorch dependency

---

requirements.txt

Signed-off-by: Ihar Hrachyshka <ihar.hrachyshka@gmail.com>

requirements: Move comment closer to tenacity where it belongs

---

.spellcheck-en-custom.txt
docs/subset_selection.md

This PR adds a simple high level markdown documentation for usage of Subset Selection within the sdg library.

feat: add markdown documentation for subset selection

---

constraints-dev.txt

This PR updates the constraints-dev.txt file using `tox -e constraints`.

chore: update constraints-dev.txt (2025-06-16)

---

constraints-dev.txt

This PR updates the constraints-dev.txt file using `tox -e constraints`.

chore: update constraints-dev.txt (2025-07-07)

---

constraints-dev.txt

This PR updates the constraints-dev.txt file using `tox -e constraints`.

chore: update constraints-dev.txt (2025-07-21)
