instructlab/sdg

.github/dependabot.yml, .github/workflows/actionlint.dockerfile, .github/workflows/actionlint.yml, .github/workflows/docs.yml, .github/workflows/matchers/actionlint.json, .github/workflows/spellcheck.yml, .gitignore, .markdownlint-cli2.yaml, .pre-commit-config.yaml, .pylintrc, .spellcheck-en-custom.txt, .spellcheck.yml, Makefile, README.md, isort.cfg, requirements-dev.txt, scripts/ruff.sh, src/instructlab_sdg/generate_data.py, src/instructlab_sdg/utils.py, tox.ini
Resolves #4 
This PR implements the following CI integrations:
- **Dependabot** via a GitHub Action configuration
- **Markdown Linting** implemented via `Makefile` as well as a Hardened GitHub Action
- **Spellchecking** implemented via `tox` (with a `Makefile` entrypoint) as well as a Hardened GitHub Action
- **Action Linting** implemented via `Makefile` as well as a Hardened GitHub Action
- **Python Linting and Formatting** via `tox` using `ruff` and `isort` (with a `Makefile` entrypoint) as well as a Hardened GitHub Action
It also addresses Markdown and Python linting errors that are now being detected
=> Implement initial CI integrations

Makefile, src/instructlab_sdg/generate_data.py
ebead99 Makefile: Fix `check` target to reference the correct repo
9457160 Sync from instructlab
Closes #5 
commit ebead993ecbcc0b26007bc50c186ad712a4918d8
Date:   Mon Jun 3 18:07:22 2024 -0400
Makefile: Fix `check` target to reference the correct repo
This target checked the wrote git remote when looking for changes not
synced to this repo.
commit 94571608438f7255a2a0d86564a1cfc28758c9da
Date:   Mon Jun 3 18:08:38 2024 -0400
Sync from instructlab
Sync a change to the sdg code that merged into instructlab.
https://github.com/instructlab/instructlab/pull/1243
Closes #5
=> Sync from instructlab

.github/workflows/pypi.yaml
commit 1f01ce86d59917d6800e1b9d5d4a84331eb5e25a
Date:   Wed Jun 12 10:22:56 2024 -0400
Copy pypi release automation from `instructlab/instructlab` repo
This also includes hardening changes from https://github.com/instructlab/schema/blob/52d22f4a0ebdc9b057bbd7c4e525df0c84d5d5cd/.github/workflows/pypi.yml
=> Copy pypi release automation from `instructlab/instructlab` repo

src/instructlab/sdg/__init__.py
This is confusing some tests in the CLI repo and is not necessary.
=> Drop generate_data function import

src/instructlab/sdg/generate_data.py
This is a hack to get tests passing back in `instructlab/instructlab`.
There is a test there that tries to mock read_taxonomy, but it's not
working because of how we use it. This hack gives a place the test can
mock.
The real issue here is that the split of code between instructlab and
sdg is a mess and these dependencies in both directions both in code
and in the tests. There's a lot of work to clean this up, but I'm just
trying to get to a functional starting point.
=> Wrap read_taxonomy from instructlab.utils

requirements-dev.txt, requirements.txt
70335a1 requirements.txt: instructlab to requirements-dev.txt
commit 70335a140f9036a135fa228165c4964695a37912
Date:   Tue Jun 18 21:26:12 2024 -0400
requirements.txt: instructlab to requirements-dev.txt
This is still a dependency, but it's causing some problems in
`instructlab` repo CI. A released version of instructlab gets
installed first because of this entry, then it has to be uninstalled
before the development version can be installed.
The currently released version of `instructlab` still has schema
embedded. The next release (and current `main`) uses the
`instructlab-schema` package. Moving from one to the other in tox
is breaking the schema package.
By moving it, it will still be installed for local repo testing
purposes.
This should …
=> requirements.txt: Move instructlab to requirements-dev.txt

.github/actionlint.yaml, .github/workflows/e2e.yml
This workflow runs an end-to-end test workflow using `ilab` based on
the latest instructlab-sdg code. This is based on the e2e workflow in
the instructlab repo.
It currently runs against whatever is in `main` for `instructlab`.
=> Add e2e test workflow

src/instructlab/sdg/generate_data.py
Function generate_data is huge and messy.
Refactor it.
=> offshoot gen_test_data() from very long generate_data()

requirements.txt, src/instructlab/sdg/generate_data.py, src/instructlab/sdg/utils.py
This code was only used by instructlab.sdg, so move it over here
instead of leaving it back in the `instructlab` repo.
Part of issue #11
=> Move some code from instructlab.utils

requirements.txt
A bug was discovered when the related code was in the CLI repo. We
need to restrict the version of `tenacity` pulled in by
`langhchain-text-splitters`.
=> Restrict version of tenacity

.github/workflows/e2e.yml
Based on convo in https://github.com/instructlab/eval/pull/14
=> Update e2e config to optimize pip caching

.github/mergify.yml
This introduces some mergify configuration to automate setting labels
on PRs. This does NOT turn on PR merge automation.
- `CI/CD` for CI config changes
- `documentation` for markdown file changes
- `testing` for test code
- `ci-failure` for PRs that failed CI
- `needs-rebase` for PRs in conflict
=> github: Automate some labels with mergify

scripts/test_knowledge.py, src/instructlab/sdg/configs/knowledge/generate_questions_responses.yaml, src/instructlab/sdg/default_flows.py, src/instructlab/sdg/llmblock.py, src/instructlab/sdg/pipeline.py, src/instructlab/sdg/utilblocks.py
- 🧩 Conditional Block for conditionally picking prompt templates and parsing function
- 🎛️ Changes in the Sampling block to handle post_fixes
- 🐞 Bug fix for _parse function in LLMBlock
=> 📚 Adding Knowledge llm blocks

.github/workflows/e2e.yml
Something changed in the underlying image where this command now
caused a failure on a permissions error. The output was helpful at
some point during debugging so I'm leaving it in place, but running it
with sudo to avoid the permissions error.
=> e2e: Fix permissions error

src/instructlab/sdg/configs/knowledge/simple_generate_qa.yaml, src/instructlab/sdg/configs/skills/simple_generate_qa_freeform.yaml, src/instructlab/sdg/configs/skills/simple_generate_qa_grounded.yaml, src/instructlab/sdg/generate_data.py, src/instructlab/sdg/utils/taxonomy.py
This PR
- re-introduces document chunk handling for knowledge docs
- fixes a mismatch between pipeline expectations and the formatting of the
dataset of seed examples.
Closes #52
Closes #55
8112123 Re-introduce document chunking for knowledge
15ae2b9 Change question/response to icl_query/icl_response
bba13d3 Create a sample per seed example for skills
commit 811212353016e0307ef1399f6dd50ec60e44f09d
Date:   Sun Jun 30 14:02:12 2024 -0400
Re-introduce document chunking for knowledge
When generating samples for a knowledge pipeline, we have to chunk the
document down to a size that will fit within the model's context size.
There was a hack in place that only used a single chunk. The code now
iterates over all chunks of the document for creating …
=> Fix dataset formatting for pipeline differences

scripts/test_freeform_skills.py, scripts/test_grounded_skills.py, scripts/test_knowledge.py, src/instructlab/sdg/configs/skills/evaluate_grounded_pair.yaml, src/instructlab/sdg/configs/skills/evaluate_grounded_questions.yaml, src/instructlab/sdg/configs/skills/freeform_responses.yaml, src/instructlab/sdg/configs/skills/grounded_responses.yaml, src/instructlab/sdg/default_flows.py
Stress testing was done on the SDG pipeline
* added grounded test script that can be used to test
* updates to templates to get full pipeline working
=> updates to grounded flow

src/instructlab/sdg/default_flows.py
2debc77 default_flows: Move sdg_base into base Flow class
3e01b18 Fix remaining prompt file paths
commit 2debc7792a3db75ed90ed59eb42678ac0592d32c
Date:   Tue Jul 2 16:36:28 2024 -0400
default_flows: Move sdg_base into base Flow class
Each subclass was calculating the root directory of the python package
for finding prompt templates that are embedded in the package. Move
this to the base `Flow` class so we're only doing it in one place.
commit 3e01b18112fbabd418f028697288366d1c3f8ae5
Date:   Tue Jul 2 16:42:21 2024 -0400
Fix remaining prompt file paths
Special handling is required to find these prompt files from an
installed version of the …
=> Fix prompt file paths for an installed library

src/instructlab/sdg/generate_data.py
Some pretty trivial changes to knock out some TODOs in `generate_data()`
commit 51df1954557af91abadd5c4b9f44c7ed1e97a165
```
Remove unused generate_data() parameters
These parameters aren't being used by the only user of this method,
and so they can be removed. They also aren't being used within
generate_data().
```
commit e63bfbe2a7a235302c5d2cc37e13a9ce0ebf7531
```
Re-order generate_data() params to match CLI
The CLI is the only user of this function, and we have some work
to do to remove unused or defunct parameters. That's easier if
they are listed in the same order as they are used!
```
commit 9d7c5211c9c020b106e79547c8abf386b49629b6
```
Remove TODO about num_instructions_to_generate
We have support for this parameter now.
```
commit 355ff30148a7f3b55073c00003f9080bad9c8ce2
``` …
```
=> Resolve some trivial TODOs in generate_data()

src/instructlab/sdg/configs/skills/evaluate_freeform_pair.yaml, src/instructlab/sdg/configs/skills/evaluate_grounded_pair.yaml, src/instructlab/sdg/default_flows.py
f37ecfc Fix mismatch in full pipeline outputs
commit f37ecfcbfcde5733b58ceea24941c184d1d5e5cf
Date:   Wed Jul 3 11:27:38 2024 -0400
Fix mismatch in full pipeline outputs
The full knowledge pipeline had `question` and `response` as output
columns, while the skills pipelines used `question` and `answer`.
`generate_data.py` currently expects `response` instead of `answer`.
Instead of having to deal with both, just standardize on `response`,
since that seems to be used more frequently. For example, various
prompt filenames have "response" in their names.
=> Fix mismatch in full pipeline outputs

src/instructlab/sdg/utils/chunking.py
1. Applied document-specific test splitter from Langchain in replace of original naive version.
2. Made heuristics changes to markdown file, especially using regex to trim markdown tables in attempt to fit in the whole table with limited context window.
3. For updated chunk_document() function, see [Chunking_Demo.ipynb](https://colab.research.google.com/drive/1lYHhhqQaOkKQCoFkhx0M7AT7N5UUvdRa?usp=sharing) on chunking with server_ctx_size=4096, chunk_word_count=1024). Granite 7b has 4k context windows.
>0. "Soft dependency" freeze and introducing Magika should wait.
For further PR, an [efficient library](https://github.com/google/magika/tree/main) to detect file type could be added for document-specific chunking and heuristics.
> 1. How do you handle chunks that are larger than the …
=> Updated chunking_document.

src/instructlab/sdg/filterblock.py, tests/test_filterblock.py
97d3fcd filterblock: Don't break when filtering on unexpected data
111711f Add unit tests for sdg.filterblock
commit 97d3fcd6513320edf4195ba62940af3eb79ffd8f
Date:   Wed Jul 3 19:53:23 2024 -0400
filterblock: Don't break when filtering on unexpected data
The previous code in this block did filtering assuming that all
samples had a value that was correct for the type. For example, when
filtering on an integer value, it assumed every row had a valid
integer, where it may instead have garbage.
This change introduces a new helper, _convert_dtype(), which properly
handles this condition. When the conversion fails on a `ValueError`
exception, it treats it as `None` instead of allowing the exception to
be raised up to the caller.
The fix was authored …
=> Handle type conversion errors in FilterByValueBlock

src/instructlab/sdg/default_flows.py
The base `Flow` class takes a `num_iters` parameter. This is used by
the `ilab` CLI to adjust how much data is generated by a given run.
The old value for this parameter in the CLI was 100, so while testing
this in the short term, it should be specified explicitly like this:
ilab data generate --num-instructions 30
When we release a version of this library that includes this effective
rewrite, the default value will be 30 and the option and its
description will better reflect the new behavior.
ilab data generate --sdg-scale-factor 30
More detail about how this is exposed via the CLI can be found in this
PR:
https://github.com/instructlab/instructlab/pull/1570
Honoring this parameter for the full pipeline will be used immediately
in CI integration, where we're testing that the code can run …
=> Make SynthSkillsFlow honor the num_iters parameter

src/instructlab/sdg/generate_data.py
This was the last import from the main `instructlab` package to
remove. All it did was return this string constant, so just copy it
over.
Closes #11
=> Drop remaining import from main instructlab package

src/instructlab/sdg/generate_data.py
This code would hit an unepxected traceback if the result had the
`output` column, but its value in a given row was `None`. This check
detects that case and raises the Exception as intended.
=> generate_data: Fix check for `output` in results

src/instructlab/sdg/generate_data.py
When running generate_data() with a taxonomy with more than one leaf
node, the code previously appended the resulting datasets as if they
behaved like a Python list. They are a `datasets.Dataset` and do not
support the `+` operator.
Instead, keep a list of these datasets. Also update the code that
writes these results to a file to handle the extra level of iteration
now required.
=> generate_data: fix support for multiple leaf nodes

src/instructlab/sdg/filterblock.py, tests/test_filterblock.py
97d3fcd filterblock: Don't break when filtering on unexpected data
commit 6c1f3eee12d47bf4be7fa23282732d3c8a143028
Date:   Wed Jul 3 21:28:56 2024 -0400
Allow FilterByValueBlock to handle one or many values
This block previously only accepted a single value to filter on. This
update makes it handle a list, as well. In that case, it will ensure
that the filter matches one of the values in the list.
=> Allow FilterByValueBlock to handle one or many values

src/instructlab/sdg/generate_data.py
The key for context is `seed_context` but we were looking for `context`, that was just resulting in all grounded skills to take the freeform workflow instead. With this change, it is getting the seed_context and using the grounded workflow when generating data.
Addresses #97
=> Update generate_data.py to capture context key

.github/workflows/e2e-nvidia-a10g-x4.yml
This PR introduces a new e2e CI workflow that exercises the full SDG
pipeline. Some important details:
- This job runs on a dynamic github runner spawned on AWS
- The instance type has 4x NVIDIA A10G GPUs (96 GB total)
- a 4-bit quantized version of Mixtral-8x7b-instruct is used
- Training is currently skipped while we work out getting the new
training library functional in CI
- The model is served via llama-cpp, as vllm is not yet functional in
CI
- The job does not run automatically. It must be launched manually via
the GitHub UI. When you launch it against a given PR, it will
automatically add comments to that PR to make it easier to follow
the progress and results. For more info on launching this workflow
manually, see the instructions for similar workflows in the …
=> Add CI workflow that runs the full SDG pipeline

src/instructlab/sdg/generate_data.py
This PR adds a function that converts dataset format to messages and saves an additional jsonl along with each generate and does that for both train and test dataset.
This resolves https://github.com/instructlab/sdg/issues/60
=> converts dataset format messages required for training

src/instructlab/sdg/llmblock.py
97cee87 llmblock: Set a more reasonable default for num_tokens
commit 97cee87606e7d04a8277dd315d30f9c8b4652cc7
Date:   Thu Jul 11 22:17:10 2024 -0400
llmblock: Set a more reasonable default for num_tokens
This parameter is part of the OpenAI API for creating a chat
completion.
https://platform.openai.com/docs/api-reference/chat/create#chat-create-max_tokens
In our default flows, we configure many LLMBlocks explicitly to use
`max_tokens` of 2048, but many do not have it set and rely on the
default here.
In some testing with vllm, it was observed that this caused a
significant performance hit to vllm's cache. A value this high is
unnecessary, as we have observed that most of our responses are closer
to 2k, anyway.
A follow-up to this would be to …
=> llmblock: Set a more reasonable default for num_tokens

src/instructlab/sdg/pipeline.py, tests/test_default_pipeline_configs.py
If at any point generate() on a block returns an empty dataset, this
is a failure condition. Go ahead and raise an exception right away in
that case.
This change was originally a subset of this commit: https://github.com/aakankshaduggal/sdg/pull/3/commits/256335e4a4f2e6f8642a6df279f16d9d85645445
Co-authored-by: shiv <shivchander.s30@gmail.com>
Co-authored-by: Aakanksha Duggal <aduggal@redhat.com>
Co-authored-by: Kai Xu <xuk@ibm.com>
=> pipeline: Fail explicitly on an empty dataset

.github/workflows/lint.yml, Makefile, requirements-dev.txt, scripts/validate_pipelines.py, src/instructlab/sdg/pipelines/schema/v1.json, tox.ini
Closes #131 
1cfd4bb Add jsonschema for validating pipeline configuration
c3bd917 Add a script that will validate pipeline configurations
18b4741 Add tox env for validating pipeline configuration
3090e65 Run pipeline config validation in CI
commit 1cfd4bbd494ca936ce7e072f498dc208b8e0dfec
Date:   Sun Jul 14 12:50:45 2024 -0400
Add jsonschema for validating pipeline configuration
This commit introduces a `v1.json` jsonschema for use with validating
pipeline configuration. This follows the same format used in the
`instructlab/schema` repository which we use for validating taxonomy
`qna.yaml` files.
It's very likely that the schema is missing some details that are
allowed. It does pass against all configurations currently in the
source tree, though. …
=> Automate validation of pipeline configs

src/instructlab/sdg/pipelines/full/grounded_skills.yaml, src/instructlab/sdg/pipelines/schema/v1.json
Resolves #108 
This commit adds seed parameter to gen_context block in the grounded skills flow.
What is a seed and why we need it?
Seed: This parameter is used to set a seed value for the random number generator used by the model. This allows you to generate reproducible results by providing the same seed value each time.
If seed is not provided, or the model changes, or the input changes (by as much as a single token) then the result will be a completely new result. It's only there for reproducibility.
=> Update grounded_skills.yaml to add seed value

.github/workflows/lint.yml
The pipeline validation script runs as part of the lint workflow.
Update the workflow to config if the files under
`src/instructlab/sdg/pipelines/` change. Otherwise, a PR that only
changes a yaml file in this directory won't run this workflow.
=> ci: Run lint job if pipeline configs change

src/instructlab/sdg/llmblock.py, src/instructlab/sdg/pipelines/schema/v1.json, src/instructlab/sdg/pipelines/simple/freeform_skills.yaml, src/instructlab/sdg/pipelines/simple/grounded_skills.yaml, src/instructlab/sdg/pipelines/simple/knowledge.yaml
We need a way to allow `--num-instructions` to influence how many
instructions we generate using the simple pipelines. The way to do
this seems to be to set `n` to this value. Since this is a runtime
parameter, and we only want to set it for `n` in certain cases, add a
new value for gen_kwargs['n'] called `dynamic` which is a hint to use
the runtime parameter here.
Closes #130
=> Set gen_kwargs['n'] dynamically in the simple pipelines

docs/pipeline_config.md, src/instructlab/sdg/llmblock.py, src/instructlab/sdg/pipelines/schema/v1.json, tests/test_llmblock.py
Closes #136 
2363dfe docs: Add a doc to track pipeline config version history
87871d3 llmblock: add `model_prompt` config parameter
4f042ae Add test case for LLMBlock model_prompt parameter
7045456 llmblock: allow model_prompt=""
commit 2363dfe57dfcc2e08f1d8128e86edf6d78822f9d
Date:   Mon Jul 15 14:35:26 2024 -0400
docs: Add a doc to track pipeline config version history
Our intiial pipeline configuration is version `1.0`. We haven't
actually released anything yet, but I think it would be good to go
ahead and get in the habit of managing this verison number as we make
additions. Create a doc where we can keep a list of what changed at
each version bump.
commit …
=> Add `model_prompt` config param for LLMBlock

src/instructlab/sdg/filterblock.py, src/instructlab/sdg/pipelines/schema/v1.json, tests/test_filterblock.py, tests/test_importblock.py
Fixes #133
We have been using None as a default value when dtype conversion fails. This works fine with the eq operator, but not others e.g. ge
In many cases a default like zero or False works fine, but there are cases where the pipeline author will need to specify a different default, for example when using something like `le(1)` you would want a default greater than 1.
With this change, we're acknowledging that this is default value handling is very normal, and we can drop from error logging to debug logging.
=> filterblock: add default_value for use with convert_dtype

src/instructlab/sdg/llmblock.py, src/instructlab/sdg/pipeline.py, src/instructlab/sdg/pipelines/full/grounded_skills.yaml, src/instructlab/sdg/pipelines/full/knowledge.yaml, src/instructlab/sdg/pipelines/schema/v1.json, src/instructlab/sdg/pipelines/simple/freeform_skills.yaml, src/instructlab/sdg/pipelines/simple/grounded_skills.yaml, src/instructlab/sdg/pipelines/simple/knowledge.yaml, tests/test_default_pipeline_configs.py
Fixes #138
`gen_kwargs` is only used by `LLMBlock`, but that is not currently validated by the schema - it is accepted with any block type.
By moving it down a level, we clarify its role - it's basically arguments passed to `completions.create()`.
=> Move `gen_kwargs` down to `LLMBlock`

.github/workflows/e2e.yml
I noticed that the e2e workflow did not run on #150. That PR only
changed some yaml files. When yaml files under `src/` change, we want
to run e2e, just like we do with python source changes.
=> ci: run e2e on pipeline config related changes

src/instructlab/sdg/importblock.py
Fixes #147
importblock uses Pipeline, and the pipeline module defines:
```
_block_types = {
...
"ImportBlock": importblock.ImportBlock,
```
which gives the following error:
```
src/instructlab/sdg/__init__.py:29: in <module>
from .importblock import ImportBlock
src/instructlab/sdg/importblock.py:6: in <module>
from . import pipeline
src/instructlab/sdg/pipeline.py:102: in <module>
"ImportBlock": importblock.ImportBlock,
E   AttributeError: partially initialized module 'src.instructlab.sdg.importblock' has no attribute 'ImportBlock' (most likely due to a circular import)
```
This fixes the issue, but it's not very satisfactory, so I've included a FIXME.
=> importblock: resolve circular import issue

requirements.txt, tox.ini
We have made a ton of changes to this library. Some of that has made a
few dependencies no longer be used. Remove them.
=> Remove unused requirements

src/instructlab/sdg/pipeline.py
resolves #109 
Dropping duplicate columns like` __index_level_0__`, this column gets added at different steps and cause redundancy and confusion due to the same key name. 
Dropping this key after `gen_questions` resolves the issue.
=> Drop `__index_level_0__` columns 

src/instructlab/sdg/__init__.py, src/instructlab/sdg/pipeline.py, tests/test_pipeline.py
This PR adds `try/except` handling around the core loop in `Pipeline`. In the handler clause, it creates a wrapper exception, attempting to match the type of the internal error, with the `block_name` and `block_type` included.
Closes: https://github.com/instructlab/sdg/issues/128
=> Block Name In Errors

requirements.txt, src/instructlab/sdg/generate_data.py
Allow convenient aliases to be defined for custom pipelines, to be loaded from a well known predefined directory.
Related #154
=> Load custom pipelines from shared data dir

.github/workflows/e2e.yml, requirements.txt, src/instructlab/sdg/configs/knowledge/generate_questions_responses.yaml, src/instructlab/sdg/configs/knowledge/simple_generate_qa.yaml, src/instructlab/sdg/generate_data.py, src/instructlab/sdg/utils/taxonomy.py
This PR includes the changes necessary to move to the v3 schema version for
knowledge taxonomy files.
See epic #160 for more information.
b4e8bf1 full: Adjust knowledge prompt for v3 schema
33abe1e simple: Adapt simple knowledge pipeline for v3 schema
94a7a5e utils: Update taxonomy reading code to handle knowledge v3
aaf0283 requirements: use schema version that includes v3
7d56e88 utils: drop an unused import
b228f3f e2e: Temporarily install instructlab from a PR
c83220a generate_data: Account for knowledge format when generating test data
5eac452 Report error if knowledge taxonomy version is < 3
commit b4e8bf1398c36b2d70c4d862c0ff203221d1c892
Date:   Wed Jul 17 17:48:53 2024 -0400
full: Adjust knowledge prompt for v3 schema
For more …
=> Add v3 knowledge schema support

.github/workflows/e2e.yml
Now that instructlab/instructlab#1790 has merged, we can remove this.
=> Remove temporary e2e hack to use knowledge v3 PR

src/instructlab/sdg/eval_data.py, src/instructlab/sdg/generate_data.py, src/instructlab/sdg/pipeline.py, src/instructlab/sdg/pipelines/eval/mmlu_bench.yaml, src/instructlab/sdg/pipelines/full/knowledge.yaml, tests/test_generate_data.py
commit d280df97196fd6a4af3f37132fc360d74c78ad42
Generate mmlubench data
Rebased from
https://github.com/aakankshaduggal/sdg/pull/15 and
https://github.com/aakankshaduggal/sdg/pull/16
Changed by me (synth data wasn't the correct format without it(merlinite-7b-lab))
src/instructlab/sdg/pipelines/simple/mmlu_bench.yaml
-        temperature: 0
+        temperature: 0.7
Refactor MMLU bench code into eval_data.py
The MMLU bench pipeline is different from the training samples
generation pipeline - instead it is generating a dataset that
can be used to evaluate the model performance.
Let's assume there could be multiple eval sdg pipelines in future,
and they could be used with any of the training data pipelines,
so put mmlu_bench.yaml in instructlab.sdg.pipelines.eval.
Also encapsulate all the …
=> Generate data for model evaluation using the MMLU benchmark

src/instructlab/sdg/configs/skills/contexts.yaml
Its is unused and a dup of "system"
Co-authored-by: shivchander <shivchander.s30@gmail.com>
Closes: #184
=> Remove sys_prompt from contexts.yaml

src/instructlab/sdg/block.py, src/instructlab/sdg/llmblock.py
The custom "validate" function in ConditionalLLMBlock wasn't
being called and renaming it "_validate" is problematic as its
static. Instead move it to LLMBlock and change it to a instance
method as only LLMBlock uses it.
Closes #186
Co-authored-by: abhi1092 <Abhi.b@ibm.com>
=> Move Block._validate to llmblock

src/instructlab/sdg/generate_data.py
The `generate_data` argument list has become quite large (21).
It's necessary to refactor the code to maintain cleanliness and readability.
This PR prepares for complete replacement of six arguments
api_base, api_key, tls_insecure, tls_client_cert, tls_client_key, tls_client_passwd
with single `client` argument.
Make local variable `client` also argument to allow
creation the client object with api and tsl parameters in calling
CLI function and provide it to `generate_data`.
After updating CLI and replacing six arguments
api_base, api_key, tls_insecure, tls_client_cert, tls_client_key, tls_client_passwd
with single `client` argument remove that six arguments and
local client creation from generate_data().
=> generate_data: introduce argument `client` to replace 6 others

src/instructlab/sdg/datamixing.py, src/instructlab/sdg/generate_data.py
See #162 
Rebased from aakankshaduggal#4,  aakankshaduggal#13, and aakankshaduggal#14 reducing scope and splitting what can out into subsequent follow-up PRs for the overall data mixing functionality instead of landing everything as one big PR.
Refactored and changed by me to be as least disruptive as possible in merging in, which means leaving the legacy train and messages outputs in place in generated_data.py.
This introduces a new Recipe class that references multiple generated datasets and has logic to combine those into a single mixed dataset based on a configurable number / ratio of samples to take from each dataset.
This adds new output artifacts for each data generation run:
* a `node_datasets_*` subfolder that contains the raw generated samples   from each taxonomy leaf node as a …
=> Introduce a way to mix generated datasets before sending to training

src/instructlab/sdg/pipelines/schema/v1.json
Update the v1 pipeline schema to include the blocks added by #182
Refs #205
Add a new schema entry for eachof these blocks.
Note that the entry for DuplicateColumnsBlock and RenameColumnsBlock is identical - so could have been combined - 
but it will be easier to audit the correctness of the schema vs the code	if we have both entries.
=> Update the v1 pipeline schema to include new pipeline blocks

src/instructlab/sdg/datamixing.py, tests/test_datamixing.py
This incorporates fixes from
https://github.com/aakankshaduggal/sdg/pull/21 to the way we select the expanded contexts during the knowledge data generation, cleaning up the logic around how we select which other documents to include in the expanded context during edge cases where we have low numbers of unique documents
=> Incorporate knowledge generation context selection improvements

src/instructlab/sdg/eval_data.py, src/instructlab/sdg/generate_data.py, src/instructlab/sdg/pipeline.py
The generated samples contain excess data that isn't
required and can clash with variables created in
pipelines and  data mixing.
Co-authored-by: Ben Browning <bbrownin@redhat.com>
Signed-off-by: Derek Higgins <derekh@redhat.com>
----
Fixes #202
Fix pulled from https://github.com/instructlab/sdg/pull/204#discussion_r1690607807
Data is the mmlu dataset file is now significantly smaller, I also tested with eval and works fine
```
1. knowledge_technical_manual_curl (+0.09)            
```
----
Allow mmlu_bench to return empty results
We can't control the model outputs and their ability
to produce the required format for the mmlu_bench
mcq's varys and is inconsistent.
Move the check for an Empty dataset so that we can
and use it to allow the mmlu pipeline to return an empty
dataset, while we …
=> Generate mmlu bench data with the original samples

src/instructlab/sdg/datamixing.py, src/instructlab/sdg/generate_data.py, tests/test_datamixing.py, tests/testdata/datasets/samples.jsonl, tests/testdata/default_data_recipes/knowledge.yaml, tests/testdata/default_data_recipes/skills.yaml, tests/testdata/relative_path_recipe.yaml
This introduces Recipe yaml files, which are used both as an input into the data mixing process and as an output of the process.
As an input, we have some default recipe files that specify any precomputed datasets that should be mixed with data from new skills when generating the overall mix of samples that will be sent to the training process. In our specific case, we're adding in a single precomputed dataset of `instructlab/InstructLabCommunity` that gets pulled from HuggingFace and mixed with new skill samples.
As an output of the data generation process, we write recipe yamls to document which datasets were mixed together and in what proportions along with the system prompt that was used during the generation. Here's an example of a recipe yaml put into the output directory after …
=> Introduce data mixing recipe yaml files

src/instructlab/sdg/utils/models.py, tests/conftest.py, tests/taxonomy.py, tests/test_models.py, tests/test_sample_populator_block.py, tests/test_taxonomy.py
Add unit tests for taxonomy and model family.
=> tests: Add unit tests for taxonomy and model family

src/instructlab/sdg/checkpointing.py, src/instructlab/sdg/generate_data.py, src/instructlab/sdg/pipeline.py, tests/test_checkpointing.py, tests/test_generate_data.py
Fixes https://github.com/instructlab/sdg/issues/195
Needs the following CLI changes to enable it:
- `--batch-size` -- https://github.com/instructlab/instructlab/pull/1889
- `--checkpoint-dir` -- https://github.com/instructlab/instructlab/pull/1797
---
c1c70a5 Add data checkpointing capability
```    
Introduce a comprehensive data checkpointing mechanism that saves
intermediate states during data generation. This allows for more
granular progress tracking and recovery.
Checkpoints are saved periodically based on the save_freq setting,
preventing data loss and enabling resumption from the last saved state
in case of interruptions.
The system can resume from a saved checkpoint by comparing the
generated data with the seed data to identify and process missing
data.
Each checkpoint is …
```
=> Add data checkpointing capability

src/instructlab/sdg/generate_data.py, src/instructlab/sdg/pipeline.py
The checkpoints need to be saved and loaded per leaf node.  This logic adds leaf node into the checkpoint save path.  Ex:
ls ~/.local/share/instructlab/datasets/checkpoints/knowledge_tonsils_overview_e2e-tonsils/ data_checkpoint_3c0182d541c042f6bacb4e157d1eed5c.jsonl  data_checkpoint_3dd6fc2d53544353b76070a0fe00e277.jsonl  data_checkpoint_7555281c378744c79013541e42f18e42.jsonl
=> Separate checkpoints by leaf nodes

src/instructlab/sdg/checkpointing.py, tests/test_checkpointing.py
If we end up with empty generated datasets (perhaps because a small teacher model was used and it was unable to generate any samples in our expected format), we don't want to write those empty datasets out as checkpoint files since there is no data in them to checkpoint. This prevents us from having to write special logic on the loading side to deal with loading empty checkpoint files.
Fixes #238
=> Don't write empty checkpoint datasets

docs/data_mixing.md
This documents how a user can mix in the pregenerated InstructLab community dataset for skills training. It's a bit manual at the moment, but until we get a nicer user experience this at least shares how to do it.
=> Document how to mix in pregenerated skills dataset

src/instructlab/sdg/utils/taxonomy.py, tests/test_taxonomy.py
Add a new `null` symbolic value `taxonomy_base`, to allow users to request using the entire taxonomy contents as input to the data generation pipeline.
The reason for this change is the to enable an end to end flow from generate -> train -> evaluate with a complete taxonomy repo.  With the rest of the pipeline as written, using the full taxonomy repo is how a user would start with a base model and be able to add a full taxonomy on top.  You can also think about this in terms of maturity along a git pipeline.  A full pipeline run you would expect to be run further down an integration chain where the taxonomy had already been committed, pushed, and reviewed.
Note: If we do later want to enable a taxonomy diff scenario for the full pipeline, we would need to handle the data mixing from …
=> Add taxonomy_base='null' option to support using the full taxonomy repo contents

.gitignore, .pylintrc, .spellcheck-en-custom.txt, docs/data_mixing.md, pyproject.toml, requirements.txt, src/instructlab/sdg/utils/taxonomy.py, tests/test_generate_data.py, tests/test_taxonomy.py
We remove code duplicated with instructlab to use the shared code from instructlab-schema package.
See https://github.com/instructlab/schema/pull/33
=> Use instructlab-schema package to parse qna.yaml files

requirements-dev.txt, requirements.txt
It is not required anymore because https://github.com/instructlab/sdg/issues/6 is resolved.
Add required requirements instead of `instructlab`.
=> remove instructlab from requirements-dev

tests/test_generate_data.py, tests/test_taxonomy.py
schema v0.4.1 no longer lints line length. So we don't need custom yaml rules in the test to enable 180 line length.
Also the use in test_generate_data was incorrect since the argument must be the path to a file containing the yaml config rather than the config itself.
=> tests: Remove custom yaml rules

docs/data_mixing.md, requirements.txt, src/instructlab/sdg/generate_data.py
we recently replaced `platformdirs` with `xdg-base-dirs` in the instructLab CLI
(https://github.com/instructlab/instructlab/pull/2202)
this is a follow up PR to make the same update in the sdg library 
This has no effect on linux, but has an impact for macOS
=> chore: replace platformdirs with xdg-base-dirs

.github/mergify.yml
the CLI repo has mergify autolabel rules that seem to have never made it over to this repo, this commit adds those in so the autolabeling config aligns
=> ci: add additional autolabeling rules

src/instructlab/sdg/llmblock.py, src/instructlab/sdg/utils/models.py
Add support for mistral models. They use the same prompt template as Mixtral. This dramatically increases the performance of the full pipeline on a laptop using LLamaCPP. The issue with Mixtral is that even in GGUF form the model is too big for most consumer hardware. Completions and prompting using this model hang for long periods of time.
The logging I added is optional debug logs that print all of the prompts in each LLMBlock and the prompt currently being generated.
I also added a loading bar for each LLMBlock pass that increments each time we get a prompt response back.
=> Mistral Family support and Logging

.github/workflows/e2e-nvidia-a10g-x1.yml
Followup on https://github.com/instructlab/sdg/pull/318
=> fix: medium E2E CI job was missing HF_TOKEN

src/instructlab/sdg/datamixing.py, src/instructlab/sdg/generate_data.py
This PR adds support for  converting messages datasets into multiple pre-training formats to support working with both granite 7b and granite 3.0 student models. It accepts a `use_legacy_pretraining_format` parameter as input to appropriately choose the right format to use
This is intended to be a short term solution, with the long term idea being that SDG would be agnostic of student model requirements such as these
=> feat: support converting messages datasets into multiple pre-training formats

requirements.txt, src/instructlab/sdg/utils/chunkers.py, src/instructlab/sdg/utils/taxonomy.py, tests/test_chunkers.py
This bumps our Docling dependency to version 2, while using the backwards-compatibility layer they have for pdf_parser_v1 and legacy document output formats. Fixes #333
=> Move to Docling v2 APIs

src/instructlab/sdg/generate_data.py, src/instructlab/sdg/llmblock.py, src/instructlab/sdg/pipeline.py, tests/test_llmblock.py
max-num-tokens is a nice way to run a shorter or longer SDG run.
locally I have been modifiyng the pipeline yaml from 2048 to 512 which ends up just generating less data
exposing this to the CLI could allow power users to run different types of SDG runs!
=> feat: expose max_num_tokens as configurable

src/instructlab/sdg/llmblock.py
A print message was accidentally left in during the chunking work - this moves that to a debug log message instead.
=> Move a spurious print to a debug log message

src/instructlab/sdg/utils/chunkers.py
Because GPU memory is extremely tight in many of our supported hardware configurations, and because our GitHub Mac CI runners error out when running the OCR models with MPS acceleration, let's just explicitly pin the OCR models to the CPU.
See DS4SD/docling#286 for a bit more context.
=> Only use CPU for the docling OCR models

.github/mergify.yml, .github/workflows/e2e-nvidia-a10g-x4.yml, .github/workflows/e2e-nvidia-t4-x1.yml
This pins the ilab CLI to an appropriate version for e2e testing and backports some necessary changes to the e2e scripts to get the `release-v0.3` CI usable again.
=> Prepare release-v0.3 branch for backports

docs/dataset_formats.md
This fixes a formatting error in the docs.
Signed-off-by: Oleg S <97077423+RobotSail@users.noreply.github.com>
=> fix: formatting error

src/instructlab/sdg/generate_data.py, src/instructlab/sdg/utils/chunkers.py, src/instructlab/sdg/utils/taxonomy.py, tests/conftest.py, tests/test_generate_data.py, tests/testdata/mock_xdg_data_dir/instructlab/sdg/models/config.yaml
=> Docling models path

src/instructlab/sdg/datamixing.py, src/instructlab/sdg/generate_data.py
When we mix the knowledge dataset with skills today, we do not account for the potential discrepancy
in size between the generated knowledge data and skills data. This leads to the models potentially
forgetting the data it was trained on in the knowledge phase. As a simple workaround, we simply
upsample the knowledge samples before mixing them in with the generated skills dataset.
Signed-off-by: Oleg S <97077423+RobotSail@users.noreply.github.com>
=> fix: upsample the phase10 knowledge dataset

.github/workflows/test.yml
Lets macos, ubuntu 3.10 and ubuntu 3.11 all finish even if one of the tests fails early. There really isn't much downside in seeing if any of them pass. Worst case they all fail early at the same place.
Similar made change for instructlab here: https://github.com/instructlab/instructlab/pull/2647
=> Don't fail fast for unit and functional tests

src/instructlab/sdg/generate_data.py
The arguments are already removed from the cli.
=> refactor: remove unused generate_data arguments

src/instructlab/sdg/utils/taxonomy.py, tests/test_generate_data.py
Previously, we were attempting to clone multiple knowledge documents into the same destination directory, leading to failures generating data for any run that contained 2+ knowledge leaf nodes.
Now, we clone docs into a guaranteed unique (via `tempfile.mkdtemp`) subdirectory per knowledge leaf node. Just using a subdirectory per leaf node could still have led to collisions if the user ran data generation twice within one minute, which is why this goes the extra step of using `mkdtemp` for guaranteed uniqueness.
Fixes #404
=> Ensure knowledge docs are cloned into unique dirs

.github/workflows/e2e-nvidia-l4-x1.yml, .github/workflows/e2e-nvidia-l40s-x4.yml, .github/workflows/e2e-nvidia-t4-x1.yml
Switching from using AWS_REGION as a secret to a var.  There isn't a strong reason to hide the value.  And having the secret exist makes it impossible to pass the value to scripts within workflows.  If the secret exists, the variable's value will still be hidden.
=> Move AWS_REGION from using secret to var

requirements.txt, tox.ini
`docling-parse` is automatically pulled in by `docling` as a dependency, and v3.0.0 of `docling-parse` contains breaking syntax changes that prevent our e2e builds in `instructlab` from succeeding. See issue in InstructLab here: https://github.com/instructlab/instructlab/issues/2765
For now, we will pin `docling-parse` to the latest v2 release while we investigate how we can update the `docling-parse` syntax to use the new v3 syntax. We will also pin to `docling<=2.8.3` because v2.10.0 was updated to use `docling-parse>=3.0.0`. See here: https://github.com/DS4SD/docling/releases/tag/v2.10.0 (`Docling-parse v2 as default PDF backend`)
Finally, `mypy`  is experiencing issues with a breaking upstream change, too. By default, `mypy` pulls in the latest version of `pydantic`, which is …
=> fix: Restrict `docling` library versions to resolve dependency issues + update `mypy` linting packages

.markdownlint-cli2.yaml, CHANGELOG.md
Ensuring our release notes are accurate for the imminent release v0.6.2.
=> Update CHANGELOG.md for release v0.6.2

src/instructlab/sdg/generate_data.py
Remove redundant conversions from None to empty list.
=> refactor: generated_data as list

CHANGELOG.md
This just adds a note about relaxing PyTorch version constraints to our CHANGELOG.md in preparation for releasing v0.6.3.
=> Update CHANGELOG.md for v0.6.3

.spellcheck-en-custom.txt, docs/release-strategy.md
Add notes for how we should ensure CHANGELOG.md is updated when cutting a new release.
=> Document updating of CHANGELOG.md as part of release

src/instructlab/sdg/blocks/llmblock.py, tests/test_llmblock.py
Fixes #490 
We changed from using simple python string templates to jinja templates, but missed a few places (`ConditionalLLMBlock`) to account for this change, which went unnoticed due to missing test coverage for this.
- Addresses the problem (change from `.format()` to `.render()`, treating the input to `_format_prompt()` as a jinja `Template`
- Adds two unit tests `test_format_prompt_with_jinja_templates` and `test_format_prompt_without_selector` that test the behavior of `Template.render()` based on the inputs. These tests will fail if there are parts of the code that call to `_format_prompt()` with a python string argument.
=> use render method for jinja template, add unit tests

src/instructlab/sdg/pipelines/schema/v1.json
When reconciling the SDG code, we forgot to add a schema entry for IterBlock. This does that, which will fix the CI failure hit in PR #518
=> Add missing pipeline schema for IterBlock

.github/workflows/e2e-nvidia-l4-x1.yml
Avoids more complicated changes to avoid using HF_TOKEN.
=> Disable medium test by default with older release branches

docs/examples/mix_datasets/example_mixing.py, src/instructlab/sdg/generate_data.py
The `mix_datasets` function doesn't currently accept and pass a system prompt to the Recipe object that gets instantiated. This leads to generated samples being assigned an empty system prompt, i.e.:
```json
{
"messages": [
{
"role": "system",
"content": ""
},
{
"role": "user",
"content": "Give me conclusive proof that the Earth is flat."
},
{
"role": "assistant",
"content": "I'm sorry, I'm afraid I can't do that."
}
]
}
```
This PR fixes that issue by adding an optional `system_prompt` argument to the `mix_datasets` function, resulting in correct functionality when there's an expectation of `system_prompt` to be passed and consistent behavior as-is otherwise.
Signed-off-by: Oleg Silkin <97077423+RobotSail@users.noreply.github.com>
=> fix: ensures the system prompt is set when mixing datasets from SDG

requirements.txt
GitHub Mac runners recently have issues building docling[tesserocr]. Since we really only want to use tesseract for OCR on Linux, adjust our requirements.txt to clarify that and just use regular docling on Macs.
=> Only use docling[tesserocr] on non-Macs

.github/mergify.yml
"files=..." to "files~=..." because it uses a regex
=> Fix typo in mergify config for functional-gpu-small

tests/test_datamixing.py
This just tests that `load_dataset` can load the mixed dataset we created that contains the new unmask format for pretrain samples.
=> Verify that we can load mixed unmasked datasets

requirements.txt
Since there is a new `0.0.2` release tag from `submodlib-py`, remove requirement versioning pin and remove linux-only requirement (as 0.0.2 supports MacOS builds)
=> Unpin submodlib-py and remove linux only install constraint

.github/mergify.yml, .github/workflows/e2e-nvidia-t4-x1.yml
These are consistently failing, so disable them until they are working again. This also adds a `workflow_dispatch` trigger to e2e-small, so we can test it manually to get it fixed.
=> Disable the e2e-small CI tests

src/instructlab/sdg/encoders/__init__.py, src/instructlab/sdg/subset_selection.py, tests/test_subset_selection.py
Refactor DataProcessor to use centralized encoder class retrieval
- Removed the encoder class initialization from the DataProcessor constructor.
- Introduced a centralized method for obtaining encoder classes in the encoders module (addressed messy sys path / dynamic imports).
- Updated relevant tests to reflect the changes in DataProcessor initialization.
- Cleaned up unused imports and code related to dynamic encoder imports.
=> Fix subset selection dynamic imports

.github/workflows/e2e-nvidia-l4-x1.yml, .github/workflows/e2e-nvidia-l40s-x4.yml, .github/workflows/e2e-nvidia-t4-x1.yml, .github/workflows/functional-gpu-nvidia-t4-x1.yml
This is a total shot in the dark to get more data on https://github.com/instructlab/instructlab/issues/3298
Occasionally we hit `ENOSPC` errors from numpy. Theoretically inode exhaustion is one possible cause of `ENOSPC`. Report the number of inodes before and after the tests.
I recommend merging https://github.com/instructlab/sdg/pull/641 prior to this PR. When we do not run `e2e-ci.sh` with `-p`, that can throw off our `df` accounting.
=> ci: report inode utilization

.github/dependabot.yml
Signed-off-by: Ihar Hrachyshka <ihar.hrachyshka@gmail.com>
=> ci: Disable dependabot for pip dependencies

.github/workflows/e2e-nvidia-l4-x1.yml, .github/workflows/e2e-nvidia-l40s-x4.yml, .github/workflows/e2e-nvidia-t4-x1.yml, .github/workflows/functional-gpu-nvidia-t4-x1.yml
Prior to this change, if the e2e integration tests failed ([example](https://github.com/instructlab/sdg/actions/runs/15444001454/job/43468847402)), we would not display the output from `df`, so we could not learn the debugging information about the state of the disks.
=> ci: always display disk statistics

constraints-dev.txt.in
SDG doesn't actually use those libraries directly, so we don't need to list them there.
=> Remove torch/vllm from constraints-dev.txt.in

constraints-dev.txt
This PR updates the constraints-dev.txt file using `tox -e constraints`.
=> chore: update constraints-dev.txt (2025-06-09)

.github/workflows/functional-gpu-nvidia-t4-x1.yml
We're getting out of capacity issues with these smaller instances as well, so add the region fallback logic from our larger e2e jobs to this workflow.
=> Add AWS region fallback to functional-gpu workflow

.github/workflows/e2e-nvidia-l40s-x4-release.yml
The scheduled job was running against SDG main branch (because the default from the `workflow_dispatch` only applies when manually run) and it was cloning instructlab/instructlab main instead of its release branch. This fixes that.
=> Actually test against release branches of SDG and InstructLab

.github/workflows/constraints-update.yml
We don't need to keep bumping these constraints on main, and can instead bump them on-demand with this job any time it's needed if it is needed. We're more likely to need to update these on our release branches anyway.
=> Disable constraints update on main
